apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE books ( id SERIAL PRIMARY KEY, title VARCHAR(255) NOT NULL, author VARCHAR(255), price NUMERIC(10,2) NOT NULL, stock_quantity INTEGER NOT NULL );

    CREATE TABLE cart_items ( id SERIAL PRIMARY KEY, book_id BIGINT NOT NULL, title VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, quantity INTEGER NOT NULL );

    CREATE TABLE orders ( id SERIAL PRIMARY KEY, customer_name VARCHAR(255) NOT NULL, total_amount NUMERIC(10,2) NOT NULL, order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

    CREATE TABLE order_items ( id SERIAL PRIMARY KEY, order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE, book_id INTEGER, quantity INTEGER NOT NULL, price NUMERIC(10,2) NOT NULL );

    CREATE TABLE card ( id SERIAL PRIMARY KEY, order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE, ccnum VARCHAR(255) NOT NULL, expdate DATE NOT NULL, seccode VARCHAR(4) NOT NULL );

    INSERT INTO books (title, author, price, stock_quantity) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 12.99, 10), ('1984', 'George Orwell', 9.99, 15), ('To Kill a Mockingbird', 'Harper Lee', 15.50, 8);

    
