apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: 160885247530.dkr.ecr.eu-west-2.amazonaws.com/cart-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "bookstore"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: CATALOG_SERVICE_URL
          value: "http://catalog-service"
        - name: CART_SERVICE_URL
          value: "http://cart-service"
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP